name: yolo-detect
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy<2
  - pillow
  - matplotlib
  - tqdm
  - pyyaml
  - pandas
  - seaborn
  - pip
  - requests
  - opencv=4.8.0.76 
  - pip:
      - psutil
      - py-cpuinfo
      - ultralytics-thop>=2.0.0